[serverMonitor]
port = 8080

[serverMonitor.administrator]
username = "administrator"
password = "123456"

[serverMonitor.development]
enable = false

[serverMonitor.development.cors]
allowOrigins = ["*"]

[serverMonitor.thirdParty.wakapi]
enable = false
apiKey = ""
apiUrl = ""

[serverMonitor.thirdParty.github]
enable = false
personalAccessToken = ""

[serverMonitor.update]
enable = false
port = 8081
fetchInterval = 600
fetchTimeout = 600

[serverMonitor.update.fetchers.github]
owner = "home-dashboard"
repository = "home-dashboard"
personalAccessToken = ""
ghproxy = false
