[serverMonitor]
port = 8080
mock = false

[serverMonitor.administrator]
username = "administrator"
password = "123456"

[serverMonitor.development]
enable = false

[serverMonitor.development.cors]
allowOrigins = []

[serverMonitor.thirdParty.wakapi]
enable = false
apiKey = ""
apiUrl = ""

[serverMonitor.thirdParty.github]
enable = false
personalAccessToken = ""
